services:
  app:
    build: .
    container_name: zees-app
    ports:
      - "5000:5000"
    env_file:
       - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app      
    labels:
      - "prometheus-job=zees-app"

  mongo:
    image: mongo:6
    container_name: zees-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node_exporter
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongo_data:
  grafana_data:
